# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: ripple 1.0.6 ruby lib

Gem::Specification.new do |s|
  s.name = "ripple"
  s.version = "1.0.6"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Sharon Rosner"]
  s.date = "2013-10-13"
  s.description = "Ripple is a Lilypond generator."
  s.email = "ciconia@gmail.com"
  s.executables = ["pdf_booklet", "ripple"]
  s.extra_rdoc_files = [
    "LICENSE",
    "README.markdown"
  ]
  s.files = [
    "Gemfile",
    "Gemfile.lock",
    "LICENSE",
    "LYDOWN.md",
    "README.markdown",
    "Rakefile",
    "SYNTAX.markdown",
    "VERSION.yml",
    "alternative_figures_syntax",
    "bin/pdf_booklet",
    "bin/ripple",
    "examples/simple/_work.yml",
    "examples/simple/basse.rpl",
    "examples/simple/dessus.rpl",
    "lib/blank.pdf",
    "lib/defaults.yml",
    "lib/ripple.rb",
    "lib/ripple/compilation.rb",
    "lib/ripple/core_ext.rb",
    "lib/ripple/figures_syntax.rb",
    "lib/ripple/generate.rb",
    "lib/ripple/lilypond.rb",
    "lib/ripple/lyrics_syntax.rb",
    "lib/ripple/part.rb",
    "lib/ripple/pdftk.rb",
    "lib/ripple/score.rb",
    "lib/ripple/syntax.rb",
    "lib/ripple/templates.rb",
    "lib/ripple/templates/combined.ly",
    "lib/ripple/templates/figures.ly",
    "lib/ripple/templates/keyboard_part.ly",
    "lib/ripple/templates/lyrics.ly",
    "lib/ripple/templates/movement.ly",
    "lib/ripple/templates/part.ly",
    "lib/ripple/templates/score.ly",
    "lib/ripple/templates/staff.ly",
    "lib/ripple/templates/tacet.ly",
    "lib/ripple/vocal_score.rb",
    "lib/ripple/work.rb",
    "ripple.gemspec",
    "spec/core_ext_spec.rb",
    "spec/figures_syntax_spec.rb",
    "spec/lyrics_syntax_spec.rb",
    "spec/rendering_spec.rb",
    "spec/spec_helper.rb",
    "spec/syntax_spec.rb"
  ]
  s.homepage = "http://github.com/ciconia/ripple"
  s.require_paths = ["lib"]
  s.rubygems_version = "2.1.0"
  s.summary = "Ripple is a Lilypond generator."

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<directory_watcher>, [">= 1.1.1"])
      s.add_runtime_dependency(%q<jeweler2>, [">= 0"])
      s.add_runtime_dependency(%q<rspec>, ["= 2.12.0"])
      s.add_runtime_dependency(%q<directory_watcher>, [">= 1.1.1"])
    else
      s.add_dependency(%q<directory_watcher>, [">= 1.1.1"])
      s.add_dependency(%q<jeweler2>, [">= 0"])
      s.add_dependency(%q<rspec>, ["= 2.12.0"])
      s.add_dependency(%q<directory_watcher>, [">= 1.1.1"])
    end
  else
    s.add_dependency(%q<directory_watcher>, [">= 1.1.1"])
    s.add_dependency(%q<jeweler2>, [">= 0"])
    s.add_dependency(%q<rspec>, ["= 2.12.0"])
    s.add_dependency(%q<directory_watcher>, [">= 1.1.1"])
  end
end

